import type { FontFamily, FontUrl } from '@lib/decode.interface'
import type { Display } from '@lib/display'

export default function transform(
  tree: Array<FontFamily<0>>,
  display: Display
): string {
  let results: Array<string> = []
  results.push('/* generated by mmtypeface api */\n\n')
  for (const family of tree) {
    results.push(singleTransform(family, display))
  }
  return results.join('\n')
}

function singleTransform(tree: FontFamily<0>, display: Display): string {
  let results: Array<string> = []
  for (const font of tree.fonts) {
    results.push(`@font-face {
  font-family: '${tree.family}';
  src: ${urlsTransform(font.urls)};
  font-weight: ${font.weight};
  font-style: ${font.style};
  font-display: ${display};
}
`)
  }
  return results.join('\n')
}

function urlsTransform(tree: Array<FontUrl>): string {
  let results: Array<string> = []
  let root = '/fonts'
  for (const fontUrl of tree) {
    results.push(`url('${root}/${fontUrl.path}') format('${fontUrl.format}')`)
  }
  return results.join(', ')
}
